name: uqlab-citations
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - bibtexparser=1.1.0=py_0
  - ca-certificates=2019.9.11=hecc5488_0
  - certifi=2019.9.11=py36_0
  - click=7.0=py_0
  - future=0.18.0=py36_0
  - jinja2=2.10.3=py_0
  - pip=19.2.3=py36_0
  - pycodestyle=2.5.0=py_0
  - pyparsing=2.4.2=py_0
  - python-dateutil=2.8.0=py_0
  - setuptools=41.4.0=py36_0
  - wheel=0.33.6=py36_0
  - pip:
    - six==1.12.0
    - readline=8.0=hf8c457e_0
    - libgcc-ng=9.1.0=hdf63c60_0
    - tk=8.6.9=hed695b0_1003
    - python=3.6.7=h357f687_1005
    - libstdcxx-ng=9.1.0=hdf63c60_0
    - sqlite=3.30.1=hcee41ef_0
    - zlib=1.2.11=h516909a_1006
    - libffi=3.2.1=he1b5a44_1006
    - ncurses=6.1=hf484d3e_1002
    - xz=5.2.4=h14c3975_1001
    - markupsafe=1.1.1=py36h14c3975_0
    - openssl=1.1.1c=h516909a_0
